[package]
name = "tree-house-bindings"
description = "Homey Rust bindings for the tree-sitter C library"
authors = [
  "Pascal Kuthe <pascalkuthe@pm.me>",
  "Michael Davis <mcarsondavis@gmail.com>",
]
version = "0.3.2"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/helix-editor/tree-house"
readme = "../README.md"
rust-version = "1.90.0"

[features]
ropey = ["dep:ropey"]
libloading = ["dep:libloading"]

[dependencies]
libloading = { version = "0.8", optional = true }
regex-cursor = "0.1.5"
ropey = { version = "1.6", default-features = false, optional = true }
thiserror = "2.0"
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter", rev = "dff1fd868c750dbbae179fcd5c43ce987e4e0528" }
tree-sitter-language = { git = "https://github.com/tree-sitter/tree-sitter", rev = "dff1fd868c750dbbae179fcd5c43ce987e4e0528" }
web-time = "1.1"

[dev-dependencies]
tree-house-bindings = { path = ".", features = ["libloading"] }
